site_name: Project Lumina Wiki
site_url: https://melancholy-dev.github.io/Project-Lumina-Wiki/
theme:
  name: material
  icon:
    logo: fontawesome/solid/l # Placeholder logo
  #favicon: logo.ico
  features:
    - navigation.sections
    - navigation.footer
    - navigation.top
    - toc.follow
    - search.highlight
  font:
    text: Lato
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: purple
      accent: purple

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: "__span"
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

nav:
  - Home: index.md
  - Products: Products.md
  - Contributors: Contributors.md
  - Wiki Layout Guide: Wiki Layout.md
  - Narrative Universe:
    - Home: Narrative Universe/Narrative Universe.md
  - Garden 0:
    - Home: Garden 0/Garden 0.md
    - Characters:
      - The Queen: Garden 0/Characters/The Queen.md
      - The Sailor: Garden 0/Characters/The Sailor.md
      - The Seeker: Garden 0/Characters/The Seeker.md
      - The Creator: Garden 0/Characters/The Creator (G0).md
      - The Astronaut: Garden 0/Characters/The Astronaut (G0).md
      - Asha: Garden 0/Characters/Asha.md
      - Memory: Garden 0/Characters/Memory.md
      - Eyezor: Garden 0/Characters/Eyezor.md
      - Sona Wellbhart: Garden 0/Characters/Sona Wellbhart.md
      - Llyv Casanova: Garden 0/Characters/Llyv Casanova.md
      - Folding Dame: Garden 0/Characters/Folding Dame.md
      - Eira Serafini: Garden 0/Characters/Eira Serafini.md
      - Espiride Hamilton: Garden 0/Characters/Espiride Hamilton.md
      - Eyezor 0: Garden 0/Characters/Eyezor 0.md
  - Lumina Aeterna:
    - Home: Lumina Aeterna/Lumina Aeterna.md
    - Characters:
      - The Astronaut: Lumina Aeterna/Characters/The Astronaut (LA).md
      - The Creator: Lumina Aeterna/Characters/The Creator (LA).md

extra:
  social:
    - icon: simple/github
      link: https://github.com/Melancholy-Dev
    - icon: simple/discord
      link: https://discord.gg/qR6hWDKmfN
    - icon: simple/instagram
      link: https://www.instagram.com/coetusinteractive/
    - icon: simple/youtube
      link: https://www.youtube.com/@coetusinteractive

copyright: Copyright &copy; 2023 Project Lumina (CC BY-SA 4.0)
